name: Cypress Tests

on: push

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress Chrome Execution
        uses: cypress-io/github-action@v6
        with:
          e2e: 
          browser: chrome
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: /home/runner/work/CypressAutomation/CypressAutomation/cypress/reports 
             
